---
# Production environment override
# Usage : docker compose -f compose.yaml -f compose.prod.yaml up -d --wait
services:
  php:
    image: daytrack-php-prod
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      JIRA_BASE_URL: ${JIRA_BASE_URL}
      JIRA_USER_EMAIL: ${JIRA_USER_EMAIL}
      JIRA_API_TOKEN: ${JIRA_API_TOKEN}
      JIRA_TICKET_TYPES: ${JIRA_TICKET_TYPES}
    volumes:
      - db_data:/app/db

volumes:
  db_data: